---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-pi
spec:
  sparkImage:
    productVersion: 3.5.2
  mode: cluster
  mainApplicationFile: local:///stackable/spark/examples/src/main/python/pi.py
  executor:
    replicas: 1
    s3connection: 
    inline:
      host: s3.cloudfly.vn
      port: 8080
      accessStyle: Path
      credentials:
        secretClass: s3-credentials-class
  logFileDirectory: 
    s3:
      prefix: eventlogs/ 
      bucket:
        inline:
          bucketName: spark-logs 
          connection:
            inline:
              host: s3.cloudfly.vn
              port: 8080
              accessStyle: Path
              credentials:
                secretClass: s3-credentials-class