---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkHistoryServer
metadata:
  name: spark-history
spec:
  image:
    productVersion: 3.5.5
  logFileDirectory:
    customLogDirectory: /spark-logs/eventlogs/
  nodes:
    nodes:
    roleGroups:
      default:
        replicas: 1
        config:
          cleaner: true
    podOverrides:
      spec:
        containers:
        - name: spark-history
          volumeMounts:
          - name: spark-logs
            mountPath: /spark-logs/eventlogs/
        volumes:
        - name: spark-logs
          persistentVolumeClaim:
            claimName: spark-history-pvc

  sparkConf:
  