---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: load-benchmark
  namespace: spark
spec:
  sparkImage:
    custom: "docker.io/trieubui1012/spark-k8s:3.5.5-stackable25.3.0" 
    productVersion: "3.5.5" 
  mode: cluster
  mainApplicationFile: s3a://spark-apps/load-benchmark.py
  logFileDirectory:
    customLogDirectory: local:///spark-logs/eventlogs/
  driver:
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "2Gi"
        volumeMounts:
        - name: spark-logs
          mountPath: /spark-logs/eventlogs/
  volumes:
  - name: spark-logs
    persistentVolumeClaim:
      claimName: spark-history-pvc
  executor:
    replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "2Gi"
