apiVersion: v2
appVersion: 25.3.0
description: The Stackable Operator for Apache Hive
home: https://github.com/stackabletech/hive-operator
maintainers:
- name: Stackable
  url: https://www.stackable.tech
name: hive-operator
version: 25.3.0
